version: "3.9"

x-credentials-path: &credentials-path "/root/.gcp/credentials.json"

services:
  genoogle:
    build:
      context: docker/genoogle
      dockerfile: Dockerfile
    profiles:
      - donotstart
    image: raphaelsantanna/genoogle:latest
    container_name: genoogle
    stdin_open: true
    tty: true
    volumes:
      - ./conf:/app/genoogle/conf
      - ./files/databanks:/app/genoogle/databanks
      - ./files/queries:/app/genoogle/queries
  hadoop-snc:
    env_file: .env
    build:
      context: docker/hadoop-snc
      dockerfile: Dockerfile
      args:
        HADOOP_VERSION: 3.3.4
        SPARK_VERSION: 3.3.1
        ZEPPELIN_VERSION: 0.10.1
        SCALA_VERSION: 2.12.17
        GOOGLE_APPLICATION_CREDENTIALS: *credentials-path
    image: raphaelsantanna/hadoop-snc:latest
    container_name: hadoop-snc
    hostname: hadoop-snc
    stdin_open: true
    tty: true
    ports:
      - "4040:4040"
      - "8080:8080"
      - "8088:8088"
      - "8042:8042"
      - "50070:50070"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: *credentials-path
    volumes:
      - ./conf:/app/genoogle/conf
      - ./files/databanks:/app/genoogle/databanks
      - ./files/queries:/app/genoogle/queries
      - ./scripts/run_genoogle.sh:/app/genoogle/run_genoogle.sh
      - ./notebook:/usr/local/zeppelin/notebook
      - type: bind
        source: ${GOOGLE_APPLICATION_CREDENTIALS}
        target: *credentials-path
