version: "3.9"
services:
  genoogle:
    build:
      context: docker/genoogle
      dockerfile: Dockerfile
    profiles:
      - donotstart
    image: raphaelsantanna/genoogle:latest
    container_name: genoogle
    stdin_open: true
    tty: true
    volumes:
      - ./docker/genoogle/fasta:/app/genoogle/files/fasta
      - ./docker/genoogle/conf:/app/genoogle/conf
      - ./docker/genoogle/queries:/app/genoogle/queries
  hadoop-snc:
    build:
      context: docker/hadoop-snc
      dockerfile: Dockerfile
      args:
        HADOOP_VERSION: 3.3.4
        SPARK_VERSION: 3.3.1
        ZEPPELIN_VERSION: 0.10.1
        SCALA_VERSION: 2.12.17
    image: raphaelsantanna/hadoop-snc:latest
    container_name: hadoop-snc
    hostname: hadoop-snc
    stdin_open: true
    tty: true
    ports:
      - "4040:4040"
      - "8080:8080"
      - "8088:8088"
      - "8042:8042"
      - "50070:50070"
    volumes:
      - ./docker/genoogle/fasta:/app/genoogle/files/fasta
      - ./docker/genoogle/conf:/app/genoogle/conf
      - ./docker/genoogle/queries:/app/genoogle/queries
      - ./docker/hadoop-snc/notebook:/usr/local/zeppelin/notebook
